// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of pattern difficulty based on viability and probability
 */
export type PatternDifficulty = 'Impossible' | 'Hard' | 'Medium' | 'Easy';
