// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternDifficulty } from "./PatternDifficulty";

/**
 * Strategic evaluation of a hand against a specific pattern.
 *
 * Extends `AnalysisResult` with AI-specific metrics like probability,
 * difficulty, and expected value.
 */
export type StrategicEvaluation = { 
/**
 * The pattern being evaluated.
 */
pattern_id: string, variation_id: string, 
/**
 * Deficiency from validator (exact tiles needed).
 */
deficiency: number, 
/**
 * Difficulty-weighted deficiency (accounts for tile scarcity).
 */
difficulty: number, 
/**
 * Human-readable classification of difficulty.
 */
difficulty_class: PatternDifficulty, 
/**
 * Probability of completing this pattern (0.0-1.0).
 */
probability: number, 
/**
 * Expected Value: V(pattern) × P(completion).
 */
expected_value: number, 
/**
 * Pattern score if won.
 */
score: number, 
/**
 * Is this pattern still viable? (false if required tiles are dead)
 */
viable: boolean, };
